idci_step:
    serialization:
        mapping:
            form_types:
                datetime:
                    type: DateTime
                birthday:
                    type: DateTime

twig:
    form:
        resources:
            - 'IDCIStepBundle:Form:fields.html.twig'