idci_step:
    serialization:
        mapping:
            form_types:
#                integer:
#                    type: integer
#                money:
#                    type: double
#                number:
#                    type: double
#                percent:
#                    type: double
                datetime:
                    type: DateTime
                birthday:
                    type: DateTime
                time:
                    type: DateTime

twig:
    form:
        resources:
            - 'IDCIStepBundle:Form:fields.html.twig'