idci_step:
    serialization:
        mapping:
            form_types:
                birthday:
                    type: DateTime
                checkbox:
                    type: boolean
                date:
                    type: DateTime
                datetime:
                    type: DateTime
                integer:
                    type: integer
                money:
                    type: double
                number:
                    type: double
                percent:
                    type: double
                time:
                    type: DateTime

twig:
    form:
        resources:
            - 'IDCIStepBundle:Form:fields.html.twig'