imports:
    - { resource: step_types.yml }
    - { resource: path_types.yml }
    - { resource: event_actions.yml }

idci_step:
    serialization:
        mapping:
            form_types:
                birthday:
                    type: DateTime
                checkbox:
                    type: boolean
                date:
                    type: DateTime
                datetime:
                    type: DateTime
                integer:
                    type: integer
                money:
                    type: double
                number:
                    type: double
                percent:
                    type: double
                time:
                    type: DateTime

twig:
    form_themes:
        - '@IDCIStep/Form/fields.html.twig'

idci_asset_loader:
    providers:
        load_only:
           - step_editor
           - map_diagram
