idci_step:
    serialization:
        mapping:
            form_types:
                datetime: DateTime
                birthday: DateTime

twig:
    form:
        resources:
            - 'IDCIStepBundle:Form:fields.html.twig'