idci_step:
    serialization:
        mapping:
            form_types:
                birthday: DateTime
                checkbox: boolean
                datetime: DateTime
                integer:  integer
                money:    double
                number:   double
                percent:  double
                time:     DateTime

twig:
    form:
        resources:
            - 'IDCIStepBundle:Form:fields.html.twig'