idci_step:

    path_event_actions:

        abstract:
            parent:      ~
            abstract:    true
            description: ~
            extra_form_options:
                logical_expression: {extra_form_type: "text", options: {required: false}}

        add_url_query_parameter:
            parent:      abstract
            description: ""
            extra_form_options:
                key:   {extra_form_type: "text", options: {required: true}}
                value: {extra_form_type: "text", options: {required: false}}

        change_data:
            parent:      abstract
            description: ""
            extra_form_options:
                fields: {extra_form_type: "textarea", options: {required: false}}

        change_final_destination:
            parent:      abstract
            description: ""
            extra_form_options:
                final_destination: {extra_form_type: "text", options: {required: true}}

        js_confirm:
            parent:      abstract
            description: ""
            extra_form_options:
                message: {extra_form_type: "textarea", options: {required: false}}

        purge_flow_data:
            parent:      abstract
            description: ""
            extra_form_options:
                steps: {extra_form_type: "text", options: {required: true}}

    step_event_actions:

        abstract:
            parent:      ~
            abstract:    true
            description: ~
            extra_form_options:
                logical_expression: {extra_form_type: "text", options: {required: false}}

        add_link:
            parent:      abstract
            description: ""
            extra_form_options:
                link_options: {extra_form_type: "textarea", options: {required: false}}

        change_data:
            parent:      abstract
            description: ""
            extra_form_options:
                fields: {extra_form_type: "textarea", options: {required: false}}

        conditional_stop_navigation:
            parent:      abstract
            description: ""
            extra_form_options:
                rules:             {extra_form_type: "text", options: {required: false}}
                final_destination: {extra_form_type: "text", options: {required: false}}

        go_next:
            parent:     abstract
            description: ""
            extra_form_options:
                condition:         {extra_form_type: "text", options: {required: false}}
                path_index:        {extra_form_type: "integer", options: {required: false}}

        retrieve_request_data:
            parent:      abstract
            description: ""
            extra_form_options:
                property: {extra_form_type: "choice", options: {required: false, choices: {attributes: attributes, request: request, query: query, server: server, files: files, cookies: cookies, headers: headers}}}
                key: {extra_form_type: "text", options: {required: true}}
                default: {extra_form_type: "text", options: {required: false}}

        transform_data:
            parent:      abstract
            description: ""
            extra_form_options:
                fields: {extra_form_type: "textarea", options: {required: false}}
