services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Registry
    IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfigurationRegistry: ~
    IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfigurationRegistryInterface: '@IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfigurationRegistry'

    IDCI\Bundle\StepBundle\Path\Event\PathEventActionRegistry: ~
    IDCI\Bundle\StepBundle\Path\Event\PathEventActionRegistryInterface: '@IDCI\Bundle\StepBundle\Path\Event\PathEventActionRegistry'

    IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfigurationRegistry: ~
    IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfigurationRegistryInterface: '@IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfigurationRegistry'

    IDCI\Bundle\StepBundle\Path\Type\PathTypeRegistry: ~
    IDCI\Bundle\StepBundle\Path\Type\PathTypeRegistryInterface: '@IDCI\Bundle\StepBundle\Path\Type\PathTypeRegistry'

    IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfigurationRegistry: ~
    IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfigurationRegistryInterface: '@IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfigurationRegistry'

    IDCI\Bundle\StepBundle\Step\Event\StepEventActionRegistry: ~
    IDCI\Bundle\StepBundle\Step\Event\StepEventActionRegistryInterface: '@IDCI\Bundle\StepBundle\Step\Event\StepEventActionRegistry'

    IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfigurationRegistry: ~
    IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfigurationRegistryInterface: '@IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfigurationRegistry'

    IDCI\Bundle\StepBundle\Step\Type\StepTypeRegistry: ~
    IDCI\Bundle\StepBundle\Step\Type\StepTypeRegistryInterface: '@IDCI\Bundle\StepBundle\Step\Type\StepTypeRegistry'

    IDCI\Bundle\StepBundle\ConditionalRule\ConditionalRuleRegistry: ~
    IDCI\Bundle\StepBundle\ConditionalRule\ConditionalRuleRegistryInterface: '@IDCI\Bundle\StepBundle\ConditionalRule\ConditionalRuleRegistry'


    # Configurations
    IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfiguration:
        arguments: [null]
        abstract: true
    IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfigurationInterface: '@IDCI\Bundle\StepBundle\Path\Event\Configuration\PathEventActionConfiguration'

    IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfiguration:
        arguments: [null]
        abstract: true
    IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfigurationInterface: '@IDCI\Bundle\StepBundle\Path\Type\Configuration\PathTypeConfiguration'

    IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfiguration:
        arguments: [null]
        abstract: true
    IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfigurationInterface: '@IDCI\Bundle\StepBundle\Step\Event\Configuration\StepEventActionConfiguration'

    IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfiguration:
        arguments: [null]
        abstract: true
    IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfigurationInterface: '@IDCI\Bundle\StepBundle\Step\Type\Configuration\StepTypeConfiguration'

    IDCI\Bundle\StepBundle\Configuration\Worker\ConfigurationWorkerRegistry: ~
    IDCI\Bundle\StepBundle\Configuration\Worker\ConfigurationWorkerRegistryInterface: '@IDCI\Bundle\StepBundle\Configuration\Worker\ConfigurationWorkerRegistry'


    # Builder
    IDCI\Bundle\StepBundle\Path\PathBuilder: ~
    IDCI\Bundle\StepBundle\Path\PathBuilderInterface: '@IDCI\Bundle\StepBundle\Path\PathBuilder'

    IDCI\Bundle\StepBundle\Step\StepBuilder: ~
    IDCI\Bundle\StepBundle\Step\StepBuilderInterface: '@IDCI\Bundle\StepBundle\Step\StepBuilder'


    # FlowRecorder
    IDCI\Bundle\StepBundle\Flow\FlowRecorder: ~
    IDCI\Bundle\StepBundle\Flow\FlowRecorderInterface: '@IDCI\Bundle\StepBundle\Flow\FlowRecorder'


    # Factory
    IDCI\Bundle\StepBundle\Map\MapBuilderFactory: ~
    IDCI\Bundle\StepBundle\Map\MapBuilderFactoryInterface: '@IDCI\Bundle\StepBundle\Map\MapBuilderFactory'

    IDCI\Bundle\StepBundle\Navigation\NavigatorFactory: ~
    IDCI\Bundle\StepBundle\Navigation\NavigatorFactoryInterface: '@IDCI\Bundle\StepBundle\Navigation\NavigatorFactory'


    # Step
    IDCI\Bundle\StepBundle\Step\Type\HtmlStepType:
        tags:
            - { name: idci_step.step_type, alias: html }
    IDCI\Bundle\StepBundle\Step\Type\HtmlStepTypeInterface: '@IDCI\Bundle\StepBundle\Step\Type\HtmlStepType'

    IDCI\Bundle\StepBundle\Step\Type\FormStepType:
        tags:
            - { name: idci_step.step_type, alias: form }
    IDCI\Bundle\StepBundle\Step\Type\FormStepTypeInterface: '@IDCI\Bundle\StepBundle\Step\Type\FormStepType'


    # StepEvent
    IDCI\Bundle\StepBundle\Step\Event\Action\AddLinkStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: add_link }
    IDCI\Bundle\StepBundle\Step\Event\Action\AddLinkStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\AddLinkStepEventAction'

    IDCI\Bundle\StepBundle\Step\Event\Action\ChangeDataStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: change_data }
    IDCI\Bundle\StepBundle\Step\Event\Action\ChangeDataStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\ChangeDataStepEventAction'

    IDCI\Bundle\StepBundle\Step\Event\Action\ConditionalStopNavigationStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: conditional_stop_navigation }
    IDCI\Bundle\StepBundle\Step\Event\Action\ConditionalStopNavigationStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\ConditionalStopNavigationStepEventAction'

    IDCI\Bundle\StepBundle\Step\Event\Action\GoNextStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: go_next }
    IDCI\Bundle\StepBundle\Step\Event\Action\GoNextStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\GoNextStepEventAction'

    IDCI\Bundle\StepBundle\Step\Event\Action\RetrieveRequestDataStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: retrieve_request_data }
    IDCI\Bundle\StepBundle\Step\Event\Action\RetrieveRequestDataStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\RetrieveRequestDataStepEventAction'

    IDCI\Bundle\StepBundle\Step\Event\Action\TransformDataStepEventAction:
        tags:
            - { name: idci_step.step_event_action, alias: transform_data }
    IDCI\Bundle\StepBundle\Step\Event\Action\TransformDataStepEventActionInterface: '@IDCI\Bundle\StepBundle\Step\Event\Action\TransformDataStepEventAction'


    # Path
    IDCI\Bundle\StepBundle\Path\Type\ConditionalDestinationPathType:
        tags:
            - { name: idci_step.path_type, alias: conditional_destination }
    IDCI\Bundle\StepBundle\Path\Type\ConditionalDestinationPathTypeInterface: '@IDCI\Bundle\StepBundle\Path\Type\ConditionalDestinationPathType'

    IDCI\Bundle\StepBundle\Path\Type\EndPathType:
        tags:
            - { name: idci_step.path_type, alias: end }
    IDCI\Bundle\StepBundle\Path\Type\EndPathTypeInterface: '@IDCI\Bundle\StepBundle\Path\Type\EndPathType'

    IDCI\Bundle\StepBundle\Path\Type\SinglePathType:
        tags:
            - { name: idci_step.path_type, alias: single }
    IDCI\Bundle\StepBundle\Path\Type\SinglePathTypeInterface: '@IDCI\Bundle\StepBundle\Path\Type\SinglePathType'


    # PathEvent
    IDCI\Bundle\StepBundle\Path\Event\Action\AddUrlQueryParameterPathEventAction:
        tags:
            - { name: idci_step.path_event_action, alias: add_url_query_parameter }
    IDCI\Bundle\StepBundle\Path\Event\Action\AddUrlQueryParameterPathEventActionInterface: '@IDCI\Bundle\StepBundle\Path\Event\Action\AddUrlQueryParameterPathEventAction'

    IDCI\Bundle\StepBundle\Path\Event\Action\ChangeDataPathEventAction:
        tags:
            - { name: idci_step.path_event_action, alias: change_data }
    IDCI\Bundle\StepBundle\Path\Event\Action\ChangeDataPathEventActionInterface: '@IDCI\Bundle\StepBundle\Path\Event\Action\ChangeDataPathEventAction'

    IDCI\Bundle\StepBundle\Path\Event\Action\ChangeFinalDestinationPathEventAction:
        tags:
            - { name: idci_step.path_event_action, alias: change_final_destination }
    IDCI\Bundle\StepBundle\Path\Event\Action\ChangeFinalDestinationPathEventActionInterface: '@IDCI\Bundle\StepBundle\Path\Event\Action\ChangeFinalDestinationPathEventAction'

    IDCI\Bundle\StepBundle\Path\Event\Action\JsConfirmPathEventAction:
        tags:
            - { name: idci_step.path_event_action, alias: js_confirm }
    IDCI\Bundle\StepBundle\Path\Event\Action\JsConfirmPathEventActionInterface: '@IDCI\Bundle\StepBundle\Path\Event\Action\JsConfirmPathEventAction'

    IDCI\Bundle\StepBundle\Path\Event\Action\PurgeFlowDataPathEventAction:
        tags:
            - { name: idci_step.path_event_action, alias: purge_flow_data }
    IDCI\Bundle\StepBundle\Path\Event\Action\PurgeFlowDataPathEventActionInterface: '@IDCI\Bundle\StepBundle\Path\Event\Action\PurgeFlowDataPathEventAction'


    # SerializationMapper
    IDCI\Bundle\StepBundle\Serialization\SerializationMapper:
        arguments: ['%idci_step.serialization.mapping%']
    IDCI\Bundle\StepBundle\Serialization\SerializationMapperInterface: '@IDCI\Bundle\StepBundle\Serialization\SerializationMapper'


    # Configuration
    IDCI\Bundle\StepBundle\Configuration\Builder\MapConfigurationBuilder: ~
    IDCI\Bundle\StepBundle\Configuration\Builder\MapConfigurationBuilderInterface: '@IDCI\Bundle\StepBundle\Configuration\Builder\MapConfigurationBuilder'

    IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcher:
        abstract: true
        arguments: [null]
    IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcherInterface: '@IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcher'

    IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcherRegistry: ~
    IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcherRegistryInterface: '@IDCI\Bundle\StepBundle\Configuration\Fetcher\ConfigurationFetcherRegistry'

    IDCI\Bundle\StepBundle\Configuration\Worker\FormBuilderWorker:
        tags:
            - { name: idci_step.configuration.worker, alias: form_builder }

    # Logger
    IDCI\Bundle\StepBundle\Navigation\NavigationLogger:
        public: false
        arguments:
            $container: '@service_container'
    IDCI\Bundle\StepBundle\Navigation\NavigationLoggerInterface: '@IDCI\Bundle\StepBundle\Navigation\NavigationLogger'


    # DataCollector
    IDCI\Bundle\StepBundle\DataCollector\NavigationDataCollector:
        public: false
        tags:
            - { name: data_collector, template: '@IDCIStep/Collector/navigation', id: idci_step.navigation }
    IDCI\Bundle\StepBundle\DataCollector\NavigationDataCollectorInterface: '@IDCI\Bundle\StepBundle\DataCollector\NavigationDataCollector'


    # Navigator
    IDCI\Bundle\StepBundle\Form\Type\NavigatorType:
        tags:
            - { name: form.type }


    # Step
    IDCI\Bundle\StepBundle\Step\Type\Form\FormStepFormType:
        tags:
            - { name: form.type, alias: idci_step_step_form_form }

    IDCI\Bundle\StepBundle\Step\Type\Form\HtmlStepFormType:
        tags:
            - { name: form.type, alias: idci_step_step_form_html }


    # Action
    IDCI\Bundle\StepBundle\Form\Type\GoNextFormType:
        tags:
            - { name: form.type, alias: idci_step_action_form_go_next }

    IDCI\Bundle\StepBundle\Form\Type\JsConfirmFormType:
        tags:
            - { name: form.type, alias: idci_step_action_form_js_confirm }

    IDCI\Bundle\StepBundle\Form\Type\LinkFormType:
        tags:
            - { name: form.type, alias: idci_step_action_form_link }


    # Twig
    IDCI\Bundle\StepBundle\Twig\Environment:
        arguments: ['@twig.loader.chain']

    IDCI\Bundle\StepBundle\Twig\StepTwigExtension: ~
