services:

    # Registry

    idci_step.step.registry:
        class: IDCI\Bundle\StepBundle\Step\StepRegistry

    idci_step.path.registry:
        class: IDCI\Bundle\StepBundle\Path\PathRegistry


    # Factory

    idci_step.map.factory:
        class: IDCI\Bundle\StepBundle\Map\MapFactory
        arguments: [@idci_step.step.registry, @idci_step.path.registry]


    # Step

    idci_step.step.type.content:
        class: IDCI\Bundle\StepBundle\Step\Type\ContentStepType
        tags:
            - { name: idci_step.step.type, alias: content }

    idci_step.step.type.form:
        class: IDCI\Bundle\StepBundle\Step\Type\FormStepType
        tags:
            - { name: idci_step.step.type, alias: form }


    # Path

    idci_step.path.type.single:
        class: IDCI\Bundle\StepBundle\Path\Type\SinglePathType
        tags:
            - { name: idci_step.path.type, alias: single }

    idci_step.path.type.conditional:
        class: IDCI\Bundle\StepBundle\Path\Type\ConditionalPathType
        tags:
            - { name: idci_step.path.type, alias: conditional }

    idci_step.path.type.random:
        class: IDCI\Bundle\StepBundle\Path\Type\RandomPathType
        tags:
            - { name: idci_step.path.type, alias: random }

    idci_step.path.type.end:
        class: IDCI\Bundle\StepBundle\Path\Type\EndPathType
        tags:
            - { name: idci_step.path.type, alias: end }
