parameters:
    idci_step.step.registry.class: IDCI\Bundle\StepBundle\Step\StepRegistry
    idci_step.path.registry.class: IDCI\Bundle\StepBundle\Path\PathRegistry

    idci_step.step.builder.class: IDCI\Bundle\StepBundle\Step\StepBuilder
    idci_step.path.builder.class: IDCI\Bundle\StepBundle\Path\PathBuilder

    idci_step.map.builder.factory.class: IDCI\Bundle\StepBundle\Map\MapBuilderFactory

    idci_step.map.navigator.class: IDCI\Bundle\StepBundle\Flow\FlowNavigator

    idci_step.step.type.content.class: IDCI\Bundle\StepBundle\Step\Type\ContentStepType
    idci_step.step.type.form.class: IDCI\Bundle\StepBundle\Step\Type\FormStepType

    idci_step.path.type.single.class: IDCI\Bundle\StepBundle\Path\Type\SinglePathType
    idci_step.path.type.conditional_destination.class: IDCI\Bundle\StepBundle\Path\Type\ConditionalDestinationPathType
    idci_step.path.type.random_destination.class: IDCI\Bundle\StepBundle\Path\Type\RandomDestinationPathType
    idci_step.path.type.end.class: IDCI\Bundle\StepBundle\Path\Type\EndPathType

    idci_step.flow.provider.class: IDCI\Bundle\StepBundle\Flow\FlowProvider
    idci_step.flow.data_store.session.class: IDCI\Bundle\StepBundle\Flow\DataStore\SessionDataStore
    idci_step.flow.data.class: IDCI\Bundle\StepBundle\Flow\DataFlow
    idci_step.flow.descriptor.class: IDCI\Bundle\StepBundle\Flow\FlowDescriptor


services:

    # Registry

    idci_step.step.registry:
        class: %idci_step.step.registry.class%

    idci_step.path.registry:
        class: %idci_step.path.registry.class%


    # Builder

    idci_step.step.builder:
        class: %idci_step.step.builder.class%
        arguments: [@idci_step.step.registry]

    idci_step.path.builder:
        class: %idci_step.path.builder.class%
        arguments: [@idci_step.path.registry]


    # Factory

    idci_step.map.builder.factory:
        class: %idci_step.map.builder.factory.class%
        arguments:
            - @idci_step.step.builder
            - @idci_step.path.builder
            - @idci_step.map.navigator


    # Map

    idci_step.map.navigator:
        class: %idci_step.map.navigator.class%
        arguments: [@idci_step.flow.provider]


    # Step

    idci_step.step.type.content:
        class: %idci_step.step.type.content.class%
        tags:
            - { name: idci_step.step.type, alias: content }

    idci_step.step.type.form:
        class: %idci_step.step.type.form.class%
        tags:
            - { name: idci_step.step.type, alias: form }


    # Path

    idci_step.path.type.single:
        class: %idci_step.path.type.single.class%
        tags:
            - { name: idci_step.path.type, alias: single }

    idci_step.path.type.conditional_destination:
        class: %idci_step.path.type.conditional_destination.class%
        tags:
            - { name: idci_step.path.type, alias: conditional_destination }

    idci_step.path.type.random_destination:
        class: %idci_step.path.type.random_destination.class%
        tags:
            - { name: idci_step.path.type, alias: random_destination }

    idci_step.path.type.end:
        class: %idci_step.path.type.end.class%
        tags:
            - { name: idci_step.path.type, alias: end }


    # Flow

    idci_step.flow.provider:
        class: %idci_step.flow.provider.class%
        arguments:
            - @idci_step.flow.data_store.session
            - @jms_serializer
            - %idci_step.flow.data.class%
            - %idci_step.flow.descriptor.class%

    idci_step.flow.data_store.session:
        class: %idci_step.flow.data_store.session.class%
        arguments: [@session]
        tags:
            - { name: idci_step.flow.data_store, alias: session }