idci_step:

    step_types:

        abstract:
            parent:      ~
            abstract:    true
            description: ~
            extra_form_options:
                title:                 {extra_form_type: "text",     options: {required: false}}
                nav_title:             {extra_form_type: "text",     options: {required: false}}
                display_title:         {extra_form_type: "checkbox", options: {required: false, data: true}}
                description:           {extra_form_type: "text",     options: {required: false}}
                nav_description:       {extra_form_type: "text",     options: {required: false}}
                attr:                  {extra_form_type: "text",     options: {required: false}}
                is_first:              {extra_form_type: "checkbox", options: {required: false}}
                pre_step_content:      {extra_form_type: "textarea", options: {required: false}}
                data:                  {extra_form_type: "textarea", options: {required: false}}
                prevent_previous:      {extra_form_type: "checkbox", options: {required: false}}
                prevent_next:          {extra_form_type: "checkbox", options: {required: false}}
                previous_options:      {extra_form_type: "textarea", options: {required: false}}
                js:                    {extra_form_type: "textarea", options: {required: false}}
                css:                   {extra_form_type: "textarea", options: {required: false}}
                events:                {extra_form_type: "textarea", options: {required: false}}
                serialization_mapping: {extra_form_type: "textarea", options: {required: false}}

        form:
            parent:      abstract
            description: ""
            extra_form_options:
                builder:       {extra_form_type: "textarea", options: {required: false} }

        html:
            parent:      abstract
            description: ""
            extra_form_options:
                content: {extra_form_type: "textarea", options: {required: false}}
