language: php

sudo: required

services:
  - docker

php:
  - '5.6'

before_install:
  - docker-compose up -d --build
  - docker-compose run --rm php composer require idci/extra-form-bundle:~2.0
  - make composer-install options="--no-interaction"
  - make yarn cmd="install"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make phpunit
  - make phpcs
  - make karma options='--single-run'

notifications:
    on_success: never
    on_failure: always

