language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"

services: mongodb

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --dev

script: phpunit --coverage-text