IDCI\Bundle\StepBundle\Flow\Flow:
    exclusion_policy: ALL

    properties:

        currentStep:
            expose: true
            groups: [idci_step.navigation]
            serialized_name: currentStep
            type: string

        history:
            expose: true
            groups: [idci_step.navigation]
            type: IDCI\Bundle\StepBundle\Flow\FlowHistory

        data:
            expose: true
            groups: [idci_step.navigation]
            type: IDCI\Bundle\StepBundle\Flow\FlowData

        remindedData:
            expose: true
            groups: [idci_step.navigation]
            serialized_name: remindedData
            type: IDCI\Bundle\StepBundle\Flow\FlowData