IDCI\Bundle\StepBundle\Flow\FlowHistory:
    exclusion_policy: ALL

    properties:

        takenPaths:
            expose: true
            groups: [idci_step.navigation]
            serialized_name: takenPaths
            type: array

        fullTakenPaths:
            expose: true
            groups: [idci_step.navigation]
            serialized_name: fullTakenPaths
            type: array
