IDCI\Bundle\StepBundle\Flow\DataFlow:
    exclusion_policy: ALL

    properties:
        steps:
            expose: true
            groups: [idci_step.flow]
            serialized_name: steps
            type: array