IDCI\Bundle\StepBundle\Flow\FlowDescriptor:
    exclusion_policy: ALL

    properties:
        takenPaths:
            expose: true
            groups: [idci_step.flow]
            serialized_name: takenPaths