IDCI\Bundle\StepBundle\Flow\FlowHistory:
    exclusion_policy: ALL

    properties:
        doneSteps:
            expose: true
            groups: [idci_step.flow]
            serialized_name: doneSteps
            type: array
        fullDoneSteps:
            expose: true
            groups: [idci_step.flow]
            serialized_name: fullDoneSteps
            type: array
        takenPaths:
            expose: true
            groups: [idci_step.flow]
            serialized_name: takenPaths
            type: array