IDCI\Bundle\StepBundle\Flow\FlowHistory:
    exclusion_policy: ALL

    properties:
        takenPaths:
            expose: true
            serialized_name: takenPaths
            type: array

        fullTakenPaths:
            expose: true
            serialized_name: fullTakenPaths
            type: array