IDCI\Bundle\StepBundle\Flow\FlowDescriptor:
    exclusion_policy: ALL

    properties:
        doneSteps:
            expose: true
            groups: [idci_step.flow]
            serialized_name: doneSteps
        currentStep:
            expose: true
            groups: [idci_step.flow]
            serialized_name: currentStep