version: '3.3'

services:

  php:
    image: idci-step-bundle/php:7.2-fpm
    build:
      context: ./php
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer

volumes:
  composer-cache: ~
